package dao;

import java.sql.Connection;
import java.sql.Statement;

import db.DBConnection;

public class UserDAO {

    public void createTable() {
        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement()) {

            String sql = "CREATE TABLE  users ("
                       + "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                       + "name VARCHAR2(100), "
                       + "email VARCHAR2(100))";

//            stmt.execute(sql);
            System.out.println("Table 'users' created successfully!");

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error creating table!");
        }
    }

    public void insertDummyData() {
        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement()) {

            String sql1 = "INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com')";
            String sql2 = "INSERT INTO users (name, email) VALUES ('Jane Smith', 'jane@example.com')";

            stmt.executeUpdate(sql1);
            stmt.executeUpdate(sql2);
            System.out.println("Dummy data inserted successfully!");

        } catch (Exception e) {
//            e.printStackTrace();
            System.out.println("Error inserting data!"+ e.getMessage());
        }
    }
}
